# Generated by Django 5.1.2 on 2024-11-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_commen_created_0e6ed4_idx_comments_created_9b3f77_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
